### ISSUE TITLE
empty myPhotos create error if user do not have photos

### ISSUE THREAD

**Issue by chavda-bhavik** [dhaval1624/prasang#8]
![image](https://user-images.githubusercontent.com/50201755/104156256-b9e4ff80-540e-11eb-824d-ff8ed6730626.png)

@dhaval1624  for user with user10@gmail.com and password user101234 create this error in myPhotos

**Comment by chavda-bhavik** [comment]
@dhaval1624  you can write below code in MyAllPhotos.tsx component
` if (photo || photo[0].length == 0) { `

**Comment by dhavalparmar1610** [comment]
![image](https://user-images.githubusercontent.com/61074359/104164469-f835eb00-541d-11eb-96c3-9f5382fbe9a8.png)

That was already resolved
